default: &defaultConfig
  flask: &flaskConfig
    name: 'WCPR'
    name_long: 'WCPR - Castle Point Radio'
    host: 'localhost'
    port: 5001
    SECRET_KEY:
    PREFERRED_URL_SCHEME: https  # http or https
    APPLICATION_ROOT: '/'
    DEBUG: True
    ASSETS_DEBUG: True
  github:
    branch: master
    webhook_secret:
  pidfile: 740.pid
  now_playing: '\\storage01.stevens.edu\w3wcpr$\now_playing.json'
  tunein:
    station_id:
    partner_id:
    partner_key:


dev:
  <<: *defaultConfig


prod: &prodConfig
  <<: *defaultConfig
  flask:
    <<: *flaskConfig
    DEBUG: False
    ASSETS_DEBUG: False
